# Generated by Django 3.1.3 on 2020-11-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
