# Generated by Django 3.1.3 on 2020-11-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20201127_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='result',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.child'),
        ),
    ]
