# Generated by Django 3.1.3 on 2020-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20201127_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='D_O_B',
            field=models.DateField(),
        ),
    ]
